# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='department',
        ),
    ]
