# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_remove_employeeuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='temp_address',
            field=models.CharField(default='IN', max_length=30),
        ),
    ]
