# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accChildId', models.AutoField(primary_key=True, serialize=False)),
                ('Potential', models.CharField(max_length=200)),
                ('pipline', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('WON', 'WON'), ('LOST', 'LOST')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRisk',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('acctRisk', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='accountRisk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskapp.AccountRisk'),
        ),
    ]
