# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_emailid', models.EmailField(max_length=100)),
                ('emp_phn', models.CharField(max_length=100)),
            ],
        ),
    ]
